# Generated by Django 5.0.3 on 2024-03-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emaill',
            new_name='email',
        ),
    ]
