# Generated by Django 5.0.3 on 2024-03-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_rename_emaill_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
    ]
